/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.GUI.panels;

import principal.Conector;
import principal.GUI.MainWindow;
import guerreiro.*;
import arma.*;
import guerreiro.habilidades.*;
/**
 *
 * @author Juliano
 */
public class CreateScreen extends javax.swing.JPanel {
    MainWindow janelaPai;
    Conector conector;
    /**
     * Creates new form CreatePanel
     */
    public CreateScreen(MainWindow jPrincipal, Conector conector) {
        janelaPai = jPrincipal;
        this.conector = conector;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jClassSelector = new javax.swing.JComboBox<>();
        jLabelClasse = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelClasse1 = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelPontosRestantes = new javax.swing.JLabel();
        jTextFieldPontos = new javax.swing.JTextField();
        jPanelAtributos = new javax.swing.JPanel();
        jLabelForca = new javax.swing.JLabel();
        jBtForcaMenos = new javax.swing.JButton();
        jTextFieldForca = new javax.swing.JTextField();
        jBtForcaMais = new javax.swing.JButton();
        jLabelAgilidade = new javax.swing.JLabel();
        jBtAgilidadeMenos = new javax.swing.JButton();
        jTextFieldAgilidade = new javax.swing.JTextField();
        jBtAgilidadeMais = new javax.swing.JButton();
        jLabelInteligencia = new javax.swing.JLabel();
        jBtInteligenciaMenos = new javax.swing.JButton();
        jTextFieldInteligencia = new javax.swing.JTextField();
        jBtInteligenciaMais = new javax.swing.JButton();
        jBtForcaMais10 = new javax.swing.JButton();
        jBtForcaMenos10 = new javax.swing.JButton();
        jBtAgilidadeMais10 = new javax.swing.JButton();
        jBtAgilidadeMenos10 = new javax.swing.JButton();
        jBtInteligenciaMenos10 = new javax.swing.JButton();
        jBtInteligenciaMais10 = new javax.swing.JButton();
        jLabelJogador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelClasse2 = new javax.swing.JLabel();
        jScrollArmas = new javax.swing.JScrollPane();
        jListArmas = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(565, 415));

        jLabelTitulo.setText("Crie seu Personagem:");

        jButton1.setText("Pronto!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jClassSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elfo", "Mago", "Orc" }));
        jClassSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassSelectorActionPerformed(evt);
            }
        });

        jLabelClasse.setText("Classe:");

        jLabelNome.setText("Nome:");

        jTextFieldNome.setText("Legolas");

        jLabelClasse1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelClasse1.setText("Atributos:");

        jLabelNome1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNome1.setText("Basico");

        jLabelPontosRestantes.setText("Pontos restantes:");

        jTextFieldPontos.setEditable(false);
        jTextFieldPontos.setText("100");
        jTextFieldPontos.setAutoscrolls(false);
        jTextFieldPontos.setMinimumSize(new java.awt.Dimension(6, 34));
        jTextFieldPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPontosActionPerformed(evt);
            }
        });

        jPanelAtributos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelForca.setText("Força:");

        jBtForcaMenos.setBackground(new java.awt.Color(255, 255, 255));
        jBtForcaMenos.setText("-");
        jBtForcaMenos.setBorder(null);
        jBtForcaMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtForcaMenosActionPerformed(evt);
            }
        });

        jTextFieldForca.setEditable(false);
        jTextFieldForca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldForca.setText("0");

        jBtForcaMais.setBackground(new java.awt.Color(255, 255, 255));
        jBtForcaMais.setText("+");
        jBtForcaMais.setBorder(null);
        jBtForcaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtForcaMaisActionPerformed(evt);
            }
        });

        jLabelAgilidade.setText("Agilidade");

        jBtAgilidadeMenos.setBackground(new java.awt.Color(255, 255, 255));
        jBtAgilidadeMenos.setText("-");
        jBtAgilidadeMenos.setBorder(null);
        jBtAgilidadeMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgilidadeMenosActionPerformed(evt);
            }
        });

        jTextFieldAgilidade.setEditable(false);
        jTextFieldAgilidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAgilidade.setText("0");

        jBtAgilidadeMais.setBackground(new java.awt.Color(255, 255, 255));
        jBtAgilidadeMais.setText("+");
        jBtAgilidadeMais.setBorder(null);
        jBtAgilidadeMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgilidadeMaisActionPerformed(evt);
            }
        });

        jLabelInteligencia.setText("Inteligência");

        jBtInteligenciaMenos.setBackground(new java.awt.Color(255, 255, 255));
        jBtInteligenciaMenos.setText("-");
        jBtInteligenciaMenos.setBorder(null);
        jBtInteligenciaMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInteligenciaMenosActionPerformed(evt);
            }
        });

        jTextFieldInteligencia.setEditable(false);
        jTextFieldInteligencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldInteligencia.setText("0");

        jBtInteligenciaMais.setBackground(new java.awt.Color(255, 255, 255));
        jBtInteligenciaMais.setText("+");
        jBtInteligenciaMais.setBorder(null);
        jBtInteligenciaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInteligenciaMaisActionPerformed(evt);
            }
        });

        jBtForcaMais10.setBackground(new java.awt.Color(255, 255, 255));
        jBtForcaMais10.setText("+10");
        jBtForcaMais10.setBorder(null);
        jBtForcaMais10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtForcaMais10ActionPerformed(evt);
            }
        });

        jBtForcaMenos10.setBackground(new java.awt.Color(255, 255, 255));
        jBtForcaMenos10.setText("-10");
        jBtForcaMenos10.setBorder(null);
        jBtForcaMenos10.setPreferredSize(new java.awt.Dimension(11, 11));
        jBtForcaMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtForcaMenos10ActionPerformed(evt);
            }
        });

        jBtAgilidadeMais10.setBackground(new java.awt.Color(255, 255, 255));
        jBtAgilidadeMais10.setText("+10");
        jBtAgilidadeMais10.setBorder(null);
        jBtAgilidadeMais10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgilidadeMais10ActionPerformed(evt);
            }
        });

        jBtAgilidadeMenos10.setBackground(new java.awt.Color(255, 255, 255));
        jBtAgilidadeMenos10.setText("-10");
        jBtAgilidadeMenos10.setBorder(null);
        jBtAgilidadeMenos10.setPreferredSize(new java.awt.Dimension(11, 11));
        jBtAgilidadeMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgilidadeMenos10ActionPerformed(evt);
            }
        });

        jBtInteligenciaMenos10.setBackground(new java.awt.Color(255, 255, 255));
        jBtInteligenciaMenos10.setText("-10");
        jBtInteligenciaMenos10.setBorder(null);
        jBtInteligenciaMenos10.setPreferredSize(new java.awt.Dimension(11, 11));
        jBtInteligenciaMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInteligenciaMenos10ActionPerformed(evt);
            }
        });

        jBtInteligenciaMais10.setBackground(new java.awt.Color(255, 255, 255));
        jBtInteligenciaMais10.setText("+10");
        jBtInteligenciaMais10.setBorder(null);
        jBtInteligenciaMais10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtInteligenciaMais10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAtributosLayout = new javax.swing.GroupLayout(jPanelAtributos);
        jPanelAtributos.setLayout(jPanelAtributosLayout);
        jPanelAtributosLayout.setHorizontalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInteligencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAgilidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelForca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addComponent(jBtAgilidadeMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jBtAgilidadeMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                .addComponent(jBtForcaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jBtForcaMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                .addComponent(jBtInteligenciaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jBtInteligenciaMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                .addComponent(jTextFieldForca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jBtForcaMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jBtForcaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)))
                                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                        .addComponent(jBtInteligenciaMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jBtInteligenciaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                                        .addComponent(jBtAgilidadeMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jBtAgilidadeMais, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelAtributosLayout.setVerticalGroup(
            jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtributosLayout.createSequentialGroup()
                .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jBtForcaMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtForcaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtForcaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtForcaMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAgilidade)
                            .addComponent(jTextFieldAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtAgilidadeMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtAgilidadeMais, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtAgilidadeMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtAgilidadeMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInteligencia)
                            .addComponent(jTextFieldInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtInteligenciaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtInteligenciaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtInteligenciaMenos10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtInteligenciaMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAtributosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelForca)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jPanelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome1)
                                    .addComponent(jLabelClasse1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelClasse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPontosRestantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNome)
                                .addComponent(jClassSelector, 0, 140, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelClasse)
                    .addComponent(jClassSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClasse1)
                    .addComponent(jLabelPontosRestantes)
                    .addComponent(jTextFieldPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelJogador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelJogador.setText("Jogador 1");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelClasse2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelClasse2.setText("Escolha uma arma:");

        jListArmas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cajado", "Clava", "Machado", "Arco" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListArmas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListArmas.setSelectedIndices(new int[] {2});
        jScrollArmas.setViewportView(jListArmas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelClasse2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelClasse2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelJogador)
                            .addComponent(jLabelTitulo)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelJogador)
                .addGap(18, 18, 18)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int qtdGuerreiros=1;
        String nome = this.jTextFieldNome.getText();
        int forca = Integer.parseInt(this.jTextFieldForca.getText());
        int agilidade = Integer.parseInt(this.jTextFieldAgilidade.getText());
        int inteligencia = Integer.parseInt(this.jTextFieldInteligencia.getText());
        
        Guerreiro novoGuerreiro;
        
        int classSelec = this.jClassSelector.getSelectedIndex();
        switch (classSelec){
            case 0:
                novoGuerreiro = new Elfo(this.conector,nome, forca, agilidade, inteligencia);
                novoGuerreiro.setarComportamentoHabilidadeEsp(new AumentarAgilidade(novoGuerreiro));
                qtdGuerreiros = conector.addGuerreiro(novoGuerreiro);
              break;
            case 1:
                novoGuerreiro = new Mago(this.conector,nome, forca, agilidade, inteligencia);
                novoGuerreiro.setarComportamentoHabilidadeEsp(new Regenerar(novoGuerreiro));
                qtdGuerreiros = conector.addGuerreiro(novoGuerreiro);
              break;
            case 2:
                novoGuerreiro = new Orc(this.conector,nome, forca, agilidade, inteligencia);
                novoGuerreiro.setarComportamentoHabilidadeEsp(new AumentarDefesa(novoGuerreiro));
                qtdGuerreiros = conector.addGuerreiro(novoGuerreiro);
              break;
        }
        int selecionado = this.jListArmas.getSelectedIndex();
        
        switch(selecionado){
            case 0:
                conector.darArma(qtdGuerreiros, new Cajado());
                break;
            case 1:
                conector.darArma(qtdGuerreiros, new Clava());
                break;
            case 2:
                conector.darArma(qtdGuerreiros, new Machado());
                break;
            case 3:
                conector.darArma(qtdGuerreiros, new Arco());
                break;
        }
        //Consertar a passagem de vida
        this.janelaPai.loadGame(qtdGuerreiros);
        
        if(qtdGuerreiros >= 2){
            this.janelaPai.switchView(3);
            
            //conector.
        }
        else{
            this.resetScreen();
            this.jLabelJogador.setText("Jogador 2");
        }
        
    }                                        

    private void jClassSelectorActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jBtForcaMenosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        int valorAtual = Integer.parseInt(jTextFieldForca.getText());
        int ptsRestantes = Integer.parseInt(this.jTextFieldPontos.getText());
        
        if(valorAtual != 0 && (this.getPtsRestantes() + 1 <= 100)){
            String novoValor = Integer.toString(valorAtual-1);
            this.jTextFieldForca.setText(novoValor);
            
            addPtsRestantes(1);
        }
        
    }                                             

    private void jBtForcaMaisActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int valorAtual = Integer.parseInt(jTextFieldForca.getText());
        
        
        if(valorAtual != 100 && (this.getPtsRestantes() - 1 >=0)){
            String novoValor = Integer.toString(valorAtual+1);
            this.jTextFieldForca.setText(novoValor);
            
            subPtsRestantes(1); 
        }
    }                                            

    private void jBtAgilidadeMenosActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        int valorAtual = Integer.parseInt(this.jTextFieldAgilidade.getText());
        int ptsRestantes = Integer.parseInt(this.jTextFieldPontos.getText());
        
        if(valorAtual != 0 && (this.getPtsRestantes() + 1 <= 100)){
            String novoValor = Integer.toString(valorAtual-1);
            this.jTextFieldAgilidade.setText(novoValor);
            
            addPtsRestantes(1);
        }
    }                                                 

    private void jBtAgilidadeMaisActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int valorAtual = Integer.parseInt(this.jTextFieldAgilidade.getText());
        int ptsRestantes = Integer.parseInt(this.jTextFieldPontos.getText());
        
        if(valorAtual != 100 && (this.getPtsRestantes() - 1 >=0)){
            String novoValor = Integer.toString(valorAtual+1);
            this.jTextFieldAgilidade.setText(novoValor);
            
            subPtsRestantes(1);
        }
    }                                                

    private void jBtInteligenciaMenosActionPerformed(java.awt.event.ActionEvent evt) {                                                     
       int valorAtual = Integer.parseInt(this.jTextFieldInteligencia.getText());
        int ptsRestantes = Integer.parseInt(this.jTextFieldPontos.getText());
        
        if(valorAtual != 0 && (this.getPtsRestantes() + 1 <= 100)){
            String novoValor = Integer.toString(valorAtual-1);
            this.jTextFieldInteligencia.setText(novoValor);
            
            addPtsRestantes(1);
        }
    }                                                    

    private void jBtInteligenciaMaisActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        int valorAtual = Integer.parseInt(this.jTextFieldInteligencia.getText());
        int ptsRestantes = Integer.parseInt(this.jTextFieldPontos.getText());
        
        if(valorAtual != 100 && (this.getPtsRestantes() - 1 >=0)){
            String novoValor = Integer.toString(valorAtual+1);
            this.jTextFieldInteligencia.setText(novoValor);
            
            subPtsRestantes(1);
        }
    }                                                   

    private void jBtForcaMais10ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int valorAtual = Integer.parseInt(jTextFieldForca.getText());
        
        
        if((valorAtual+10) <= 100 && (this.getPtsRestantes() - 10 >=0)){
            String novoValor = Integer.toString(valorAtual+10);
            this.jTextFieldForca.setText(novoValor);
            
            subPtsRestantes(10); 
        }
    }                                              

    private void jBtForcaMenos10ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int valorAtual = Integer.parseInt(jTextFieldForca.getText());
        
        
        if((valorAtual-10) >= 0 && (this.getPtsRestantes() + 10 <= 100)){
            String novoValor = Integer.toString(valorAtual-10);
            this.jTextFieldForca.setText(novoValor);
            
            addPtsRestantes(10); 
        }
    }                                               

    private void jBtAgilidadeMais10ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int valorAtual = Integer.parseInt(jTextFieldAgilidade.getText());
        
        
        if((valorAtual+10) <= 100 && (this.getPtsRestantes() - 10 >=0)){
            String novoValor = Integer.toString(valorAtual+10);
            this.jTextFieldAgilidade.setText(novoValor);
            
            subPtsRestantes(10); 
        }
    }                                                  

    private void jBtAgilidadeMenos10ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        int valorAtual = Integer.parseInt(jTextFieldAgilidade.getText());
        
        
        if(((valorAtual-10) >= 0) && (this.getPtsRestantes() + 10 <= 100)){
            String novoValor = Integer.toString(valorAtual-10);
            this.jTextFieldAgilidade.setText(novoValor);
            
            addPtsRestantes(10); 
        }
    }                                                   

    private void jBtInteligenciaMenos10ActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        int valorAtual = Integer.parseInt(jTextFieldInteligencia.getText());
        
        
        if(((valorAtual-10) >= 0) && (this.getPtsRestantes() + 10 <= 100)){
            String novoValor = Integer.toString(valorAtual-10);
            this.jTextFieldInteligencia.setText(novoValor);
            
            addPtsRestantes(10); 
        }
    }                                                      

    private void jBtInteligenciaMais10ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        int valorAtual = Integer.parseInt(jTextFieldInteligencia.getText());
        
        
        if((valorAtual+10) <= 100 && (this.getPtsRestantes() - 10 >=0)){
            String novoValor = Integer.toString(valorAtual+10);
            this.jTextFieldInteligencia.setText(novoValor);
            
            subPtsRestantes(10); 
        }
    }                                                     

    private void jTextFieldPontosActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                
    private void addPtsRestantes(int qtd){
        int ptsAntigos = Integer.parseInt(this.jTextFieldPontos.getText());
        String novosPtsRestantes = Integer.toString(ptsAntigos+qtd);
        this.jTextFieldPontos.setText(novosPtsRestantes);
    }
    
    private void subPtsRestantes(int qtd){
        int ptsAntigos = Integer.parseInt(this.jTextFieldPontos.getText());
        String novosPtsRestantes = Integer.toString(ptsAntigos-qtd);
        this.jTextFieldPontos.setText(novosPtsRestantes);        
    }
    
    private int getPtsRestantes(){
        int ptsAntigos = Integer.parseInt(this.jTextFieldPontos.getText());
        return ptsAntigos;
    }
    
    
    public void resetScreen(){
   
        this.jTextFieldNome.setText("");
        this.jTextFieldPontos.setText("100");
        this.jTextFieldAgilidade.setText("0");
        this.jTextFieldInteligencia.setText("0");
        this.jTextFieldForca.setText("0");
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtAgilidadeMais;
    private javax.swing.JButton jBtAgilidadeMais10;
    private javax.swing.JButton jBtAgilidadeMenos;
    private javax.swing.JButton jBtAgilidadeMenos10;
    private javax.swing.JButton jBtForcaMais;
    private javax.swing.JButton jBtForcaMais10;
    private javax.swing.JButton jBtForcaMenos;
    private javax.swing.JButton jBtForcaMenos10;
    private javax.swing.JButton jBtInteligenciaMais;
    private javax.swing.JButton jBtInteligenciaMais10;
    private javax.swing.JButton jBtInteligenciaMenos;
    private javax.swing.JButton jBtInteligenciaMenos10;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jClassSelector;
    private javax.swing.JLabel jLabelAgilidade;
    private javax.swing.JLabel jLabelClasse;
    private javax.swing.JLabel jLabelClasse1;
    private javax.swing.JLabel jLabelClasse2;
    private javax.swing.JLabel jLabelForca;
    private javax.swing.JLabel jLabelInteligencia;
    private javax.swing.JLabel jLabelJogador;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelPontosRestantes;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListArmas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAtributos;
    private javax.swing.JScrollPane jScrollArmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAgilidade;
    private javax.swing.JTextField jTextFieldForca;
    private javax.swing.JTextField jTextFieldInteligencia;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPontos;
    // End of variables declaration                   
}
