/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.GUI.panels;
import arma.ArmaIF;
import guerreiro.Guerreiro;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import principal.Conector;
import principal.GUI.MainWindow;

/**
 *
 * @author Juliano
 */
public class GameScreen extends javax.swing.JPanel {
    MainWindow janelaPai;
    Conector conector;
    
    int vezDe = 1;
    /**
     * Creates new form GameScreen
     */
    public GameScreen(MainWindow jPrincipal, Conector conector) {
        this.janelaPai = jPrincipal;
        this.conector = conector;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGuerreirosInfo = new javax.swing.JPanel();
        jPanelGuerreiro2 = new javax.swing.JPanel();
        jLabelGuerreiro2 = new javax.swing.JLabel();
        jLabelClasse2 = new javax.swing.JLabel();
        jLabelVida2 = new javax.swing.JLabel();
        jLabelForca2 = new javax.swing.JLabel();
        jTextFieldForca2 = new javax.swing.JTextField();
        jLabelAgildade2 = new javax.swing.JLabel();
        jTextFieldAgilidade2 = new javax.swing.JTextField();
        jLabelInteligencia2 = new javax.swing.JLabel();
        jTexInteligencia2 = new javax.swing.JTextField();
        jTextArma2 = new javax.swing.JLabel();
        jLabelArmaUsadaP2 = new javax.swing.JLabel();
        jTextFieldVida2 = new javax.swing.JTextField();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanelGuerreiro1 = new javax.swing.JPanel();
        jLabelGuerreiro1 = new javax.swing.JLabel();
        jLabelClasse1 = new javax.swing.JLabel();
        jLabelVida1 = new javax.swing.JLabel();
        jLabelForca1 = new javax.swing.JLabel();
        jTextFieldForca1 = new javax.swing.JTextField();
        jLabelAgildade1 = new javax.swing.JLabel();
        jTextFieldAgilidade1 = new javax.swing.JTextField();
        jLabelInteligencia1 = new javax.swing.JLabel();
        jTexInteligencia1 = new javax.swing.JTextField();
        jTextArma1 = new javax.swing.JLabel();
        jLabelArmaUsada1 = new javax.swing.JLabel();
        jTextFieldVida = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAtacar = new javax.swing.JButton();
        jButtonHabilidade = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputScreen = new javax.swing.JTextPane();

        jPanelGuerreirosInfo.setBackground(new java.awt.Color(234, 234, 234));
        jPanelGuerreirosInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(167, 196, 255), 1, true));

        jPanelGuerreiro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabelGuerreiro2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGuerreiro2.setText("Nome Guerreiro");

        jLabelClasse2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelClasse2.setText("Classe");

        jLabelVida2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVida2.setText("Vida:");

        jLabelForca2.setText("Força:");

        jTextFieldForca2.setEditable(false);
        jTextFieldForca2.setText("0");
        jTextFieldForca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForca2ActionPerformed(evt);
            }
        });

        jLabelAgildade2.setText("Agilidade:");

        jTextFieldAgilidade2.setEditable(false);
        jTextFieldAgilidade2.setText("0");
        jTextFieldAgilidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgilidade2ActionPerformed(evt);
            }
        });

        jLabelInteligencia2.setText("Inteligen.");

        jTexInteligencia2.setEditable(false);
        jTexInteligencia2.setText("0");
        jTexInteligencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexInteligencia2ActionPerformed(evt);
            }
        });

        jTextArma2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArma2.setText("Arma:");

        jLabelArmaUsadaP2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelArmaUsadaP2.setText("Arma");

        jTextFieldVida2.setEditable(false);
        jTextFieldVida2.setText("100");
        jTextFieldVida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVida2ActionPerformed(evt);
            }
        });

        jProgressBar2.setMaximum(300);
        jProgressBar2.setValue(300);

        javax.swing.GroupLayout jPanelGuerreiro2Layout = new javax.swing.GroupLayout(jPanelGuerreiro2);
        jPanelGuerreiro2.setLayout(jPanelGuerreiro2Layout);
        jPanelGuerreiro2Layout.setHorizontalGroup(
            jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                                .addComponent(jTextArma2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelArmaUsadaP2))
                            .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                                .addComponent(jLabelVida2)
                                .addGap(10, 10, 10)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelGuerreiro2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelClasse2))))
                    .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelForca2)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldForca2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelAgildade2)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldAgilidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelInteligencia2)
                        .addGap(1, 1, 1)
                        .addComponent(jTexInteligencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelGuerreiro2Layout.setVerticalGroup(
            jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuerreiro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuerreiro2)
                    .addComponent(jLabelClasse2))
                .addGap(11, 11, 11)
                .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelVida2)
                        .addComponent(jTextFieldVida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextArma2)
                    .addComponent(jLabelArmaUsadaP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGuerreiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelForca2)
                    .addComponent(jTextFieldForca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAgildade2)
                    .addComponent(jTextFieldAgilidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInteligencia2)
                    .addComponent(jTexInteligencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanelGuerreiro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 152, 152), 3));

        jLabelGuerreiro1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGuerreiro1.setText("Nome Guerreiro");

        jLabelClasse1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabelClasse1.setText("Classe");

        jLabelVida1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVida1.setText("Vida:");

        jLabelForca1.setText("Força:");

        jTextFieldForca1.setEditable(false);
        jTextFieldForca1.setText("0");
        jTextFieldForca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldForca1ActionPerformed(evt);
            }
        });

        jLabelAgildade1.setText("Agilidade:");

        jTextFieldAgilidade1.setEditable(false);
        jTextFieldAgilidade1.setText("0");
        jTextFieldAgilidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgilidade1ActionPerformed(evt);
            }
        });

        jLabelInteligencia1.setText("Inteligen.");

        jTexInteligencia1.setEditable(false);
        jTexInteligencia1.setText("0");
        jTexInteligencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexInteligencia1ActionPerformed(evt);
            }
        });

        jTextArma1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArma1.setText("Arma:");

        jLabelArmaUsada1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelArmaUsada1.setText("Arma");

        jTextFieldVida.setEditable(false);
        jTextFieldVida.setText("100");
        jTextFieldVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVidaActionPerformed(evt);
            }
        });

        jProgressBar1.setMaximum(300);
        jProgressBar1.setValue(300);

        javax.swing.GroupLayout jPanelGuerreiro1Layout = new javax.swing.GroupLayout(jPanelGuerreiro1);
        jPanelGuerreiro1.setLayout(jPanelGuerreiro1Layout);
        jPanelGuerreiro1Layout.setHorizontalGroup(
            jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                                .addComponent(jTextArma1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelArmaUsada1))
                            .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                                .addComponent(jLabelVida1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelGuerreiro1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelClasse1))))
                    .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelForca1)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldForca1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelAgildade1)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldAgilidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelInteligencia1)
                        .addGap(1, 1, 1)
                        .addComponent(jTexInteligencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGuerreiro1Layout.setVerticalGroup(
            jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuerreiro1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGuerreiro1)
                    .addComponent(jLabelClasse1))
                .addGap(11, 11, 11)
                .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVida1)
                    .addComponent(jTextFieldVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextArma1)
                    .addComponent(jLabelArmaUsada1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGuerreiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelForca1)
                    .addComponent(jTextFieldForca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAgildade1)
                    .addComponent(jTextFieldAgilidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInteligencia1)
                    .addComponent(jTexInteligencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGuerreirosInfoLayout = new javax.swing.GroupLayout(jPanelGuerreirosInfo);
        jPanelGuerreirosInfo.setLayout(jPanelGuerreirosInfoLayout);
        jPanelGuerreirosInfoLayout.setHorizontalGroup(
            jPanelGuerreirosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuerreirosInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanelGuerreiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGuerreiro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelGuerreirosInfoLayout.setVerticalGroup(
            jPanelGuerreirosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuerreirosInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelGuerreirosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGuerreiro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGuerreiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(169, 122, 74));

        jButtonAtacar.setText("Atacar");
        jButtonAtacar.setToolTipText("Ataque normal");
        jButtonAtacar.setBorderPainted(false);
        jButtonAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtacarActionPerformed(evt);
            }
        });

        jButtonHabilidade.setText("Habilidade Especial");
        jButtonHabilidade.setToolTipText("Usar a habilidade especial da sua classe.");
        jButtonHabilidade.setBorderPainted(false);
        jButtonHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabilidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonAtacar)
                .addGap(15, 15, 15)
                .addComponent(jButtonHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(jButtonHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        outputScreen.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(outputScreen);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGuerreirosInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelGuerreirosInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabilidadeActionPerformed
        conector.sendUseHability();
        this.loadGuerreiro(1);
        this.loadGuerreiro(2);
        
    }//GEN-LAST:event_jButtonHabilidadeActionPerformed

    private void jButtonAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtacarActionPerformed
        this.clear();

        conector.ataque();
        
        if(vezDe == 1)
            vezDe = 2;
        else if (vezDe == 2)
            vezDe = 1;
        this.switchPlayer();
    }//GEN-LAST:event_jButtonAtacarActionPerformed

    private void jTextFieldAgilidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgilidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgilidade2ActionPerformed

    private void jTexInteligencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexInteligencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexInteligencia2ActionPerformed

    private void jTextFieldForca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForca2ActionPerformed

    private void jTextFieldVida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVida2ActionPerformed

    private void jTextFieldForca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldForca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldForca1ActionPerformed

    private void jTextFieldAgilidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgilidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgilidade1ActionPerformed

    private void jTexInteligencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexInteligencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexInteligencia1ActionPerformed

    private void jTextFieldVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVidaActionPerformed

    public void addText(String text){
        String textoAntigo = this.outputScreen.getText();
        if(textoAntigo.equals("")){
             this.outputScreen.setText(text);
        }
        else this.outputScreen.setText(textoAntigo +"\n" + text);
    }
    
    public void clear(){
        this.outputScreen.setText("");
        
        
    }
    public void switchPlayer(){
        Border ativo = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 152, 152), 3);
        Border naoAtivo = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3);
        if(vezDe == 1){
            this.jPanelGuerreiro1.setBorder(ativo);
            this.jPanelGuerreiro2.setBorder(naoAtivo);
        }
        else if(vezDe == 2){
            this.jPanelGuerreiro1.setBorder(naoAtivo);
            this.jPanelGuerreiro2.setBorder(ativo);
        }
    }
    
    public void mudarVida(int player, int vidaNova){
        if(player == 1){
            this.jTextFieldVida.setText(Integer.toString(vidaNova));
            this.jProgressBar1.setValue(vidaNova);
        }
        else if(player == 2){
            this.jTextFieldVida2.setText(Integer.toString(vidaNova));
            this.jProgressBar2.setValue(vidaNova);
        }
    }
    
    public void loadGuerreiro(int player){
        Guerreiro guerr = conector.getGuerreiro(player);
        
        if(player == 1){
            this.jProgressBar1.setValue(guerr.getVida());
            this.jTextFieldVida.setText(Integer.toString(guerr.getVida()));
            this.jLabelGuerreiro1.setText(guerr.getNome());
            this.jLabelClasse1.setText(guerr.getClasse());
            
            this.jTexInteligencia1.setText(Integer.toString(guerr.getInteligencia()));
            this.jTextFieldForca1.setText(Integer.toString(guerr.getForca()));
            this.jTextFieldAgilidade1.setText(Integer.toString(guerr.getAgilidade()));
            this.jLabelArmaUsada1.setText(guerr.getArma().getNome());            
        }
        else if(player == 2){
            this.jProgressBar2.setValue(guerr.getVida());
            this.jTextFieldVida2.setText(Integer.toString(guerr.getVida()));
            this.jLabelGuerreiro2.setText(guerr.getNome());
            this.jLabelClasse2.setText(guerr.getClasse());
            
            this.jTexInteligencia2.setText(Integer.toString(guerr.getInteligencia()));
            this.jTextFieldForca2.setText(Integer.toString(guerr.getForca()));
            this.jTextFieldAgilidade2.setText(Integer.toString(guerr.getAgilidade()));
            this.jLabelArmaUsadaP2.setText(guerr.getArma().getNome());    
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtacar;
    private javax.swing.JButton jButtonHabilidade;
    private javax.swing.JLabel jLabelAgildade1;
    private javax.swing.JLabel jLabelAgildade2;
    private javax.swing.JLabel jLabelArmaUsada1;
    private javax.swing.JLabel jLabelArmaUsadaP2;
    private javax.swing.JLabel jLabelClasse1;
    private javax.swing.JLabel jLabelClasse2;
    private javax.swing.JLabel jLabelForca1;
    private javax.swing.JLabel jLabelForca2;
    private javax.swing.JLabel jLabelGuerreiro1;
    private javax.swing.JLabel jLabelGuerreiro2;
    private javax.swing.JLabel jLabelInteligencia1;
    private javax.swing.JLabel jLabelInteligencia2;
    private javax.swing.JLabel jLabelVida1;
    private javax.swing.JLabel jLabelVida2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGuerreiro1;
    private javax.swing.JPanel jPanelGuerreiro2;
    private javax.swing.JPanel jPanelGuerreirosInfo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTexInteligencia1;
    private javax.swing.JTextField jTexInteligencia2;
    private javax.swing.JLabel jTextArma1;
    private javax.swing.JLabel jTextArma2;
    private javax.swing.JTextField jTextFieldAgilidade1;
    private javax.swing.JTextField jTextFieldAgilidade2;
    private javax.swing.JTextField jTextFieldForca1;
    private javax.swing.JTextField jTextFieldForca2;
    private javax.swing.JTextField jTextFieldVida;
    private javax.swing.JTextField jTextFieldVida2;
    private javax.swing.JTextPane outputScreen;
    // End of variables declaration//GEN-END:variables
}
