/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.GUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import principal.GUI.panels.*;
import principal.*;
import arma.ArmaIF;
import guerreiro.Guerreiro;
/**
 *
 * @author Juliano
 */
public class MainWindow extends javax.swing.JFrame {
    Conector conector;
    
    GridBagLayout layout = new GridBagLayout();
    
    StartScreen inicio;
    CreateScreen criar;
    GameScreen game;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(Conector conector) {
        this.conector = conector;
        initComponents();
        
        this.inicio = new StartScreen(this, conector);
        this.criar = new CreateScreen(this, conector);
        this.game = new GameScreen(this, conector);
        
        this.jPainelDinamico.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        this.jPainelDinamico.add(inicio, c);
        
        c.gridx = 0;
        c.gridy = 0;
        this.jPainelDinamico.add(criar, c);
        
        c.gridx = 0;
        c.gridy = 0;
        this.jPainelDinamico.add(game, c);
        
        inicio.setVisible(true);
        criar.setVisible(false);
        game.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelDinamico = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        Opcoes = new javax.swing.JMenu();
        jStartMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duelo de Campeões");
        setResizable(false);

        javax.swing.GroupLayout jPainelDinamicoLayout = new javax.swing.GroupLayout(jPainelDinamico);
        jPainelDinamico.setLayout(jPainelDinamicoLayout);
        jPainelDinamicoLayout.setHorizontalGroup(
            jPainelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        jPainelDinamicoLayout.setVerticalGroup(
            jPainelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        Opcoes.setText("Opções");

        jStartMenu.setText("Tela de inicio");
        jStartMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartMenuActionPerformed(evt);
            }
        });
        Opcoes.add(jStartMenu);

        jMenuBar.add(Opcoes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelDinamico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartMenuActionPerformed
        // TODO add your handling code here:
        this.restart();
        switchView(1);
        conector.resetar();
    }//GEN-LAST:event_jStartMenuActionPerformed
    public void switchView(int num){
        if(num == 1){
            this.inicio.setVisible(true);
            this.criar.setVisible(false);
            this.game.setVisible(false);
        }
        else if(num == 2){
            this.inicio.setVisible(false);
            this.criar.setVisible(true);
            this.game.setVisible(false);
        }
        else if(num == 3){
            this.inicio.setVisible(false);
            this.criar.setVisible(false);
            this.game.setVisible(true);
        }
    }
    
    //Comandos de saida(para imprimir dados na saida de texto
    public void sendReport(int player, int  vida){
        this.game.mudarVida(player, vida);
    }
    public void addText(String text){
        this.game.addText(text);
    }
    public void clearPainel(){
        this.game.clear();
    }
    
    public void restart(){
        this.criar.resetScreen();
        this.game.clear();
        switchView(1);
    }
    
    public void loadGame(int player){
        this.game.loadGuerreiro(player);
    }
  
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opcoes;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPainelDinamico;
    private javax.swing.JMenuItem jStartMenu;
    // End of variables declaration//GEN-END:variables
}
